# Generated by Django 5.0.1 on 2024-01-30 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="Redirection",
            options={"unique_together": {("site", "short_url")}},
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "short_url",
                    models.CharField(
                        help_text="The source URL, without the domain name, and without the initial slash. It must not contain any questionmark or hash sign.",
                        max_length=2000,
                        verbose_name="Short URL fragment",
                    ),
                ),
                (
                    "destination_url",
                    models.URLField(
                        help_text="The complete destination URL. Must be an absolute URL.",
                        max_length=4000,
                        verbose_name="Destination URL",
                    ),
                ),
                (
                    "http_status",
                    models.IntegerField(
                        choices=[
                            (301, "Moved permanently (301)"),
                            (302, "Found (302)"),
                            (303, "See other (303)"),
                            (307, "Temporary redirect (307)"),
                            (308, "Permanent redirect (308)"),
                        ],
                        default=302,
                        verbose_name="HTTP Status",
                    ),
                ),
                (
                    "params_mode",
                    models.CharField(
                        choices=[
                            (
                                "IGNORE",
                                "Ignore params in source URL, use only params in destination URL",
                            ),
                            (
                                "DEFAULT",
                                "Params in source URL overwrite values defined in destination URL",
                            ),
                            (
                                "ADD",
                                "Params in source URL append to but do not replace values defined in destination URL",
                            ),
                        ],
                        default="DEFAULT",
                        help_text="How should query parameters be handled.",
                        max_length=10,
                        verbose_name="Parameters handling mode",
                    ),
                ),
                (
                    "unique_counter_mode",
                    models.CharField(
                        choices=[
                            ("NONE", "Do not count unique views"),
                            ("IP", "Count by unique IP"),
                            ("SSID", "Count by unique SSID"),
                            ("QUERY_PARAMS", "Count by unique query parameters"),
                        ],
                        default="SSID",
                        help_text="From what properties of requests should the unique counter be computed",
                        max_length=15,
                        verbose_name="Unique counter mode",
                    ),
                ),
                (
                    "counter",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="Counter"
                    ),
                ),
                (
                    "unique_counter",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="Unique counter"
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
            ],
        ),
    ]
