# Generated by Django 5.0.1 on 2024-01-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djan", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redirection",
            name="destination_url",
            field=models.URLField(
                db_index=True,
                help_text="The complete destination URL. Must be an absolute URL.",
                max_length=4000,
                verbose_name="Destination URL",
            ),
        ),
    ]
